export const punchlines = [
  {
    punchline: "Peacemaker",
    good_name: "A Superhero",
    bad_name: "Vladimir Putin",
    great_name:
      "The Person in the Group Chat Who Actually Picks the Dinner Location",
  },
  {
    punchline: "One Direction",
    good_name: "A Band",
    bad_name: "An Elevator",
    great_name: "A Laxative",
  },
  {
    punchline: "Half Baked",
    good_name: "A Ben & Jerry's Flavor",
    bad_name: "A Pizzeria",
    great_name: "Snoop Dogg and Martha Steward",
  },
  {
    punchline: "All In",
    good_name: "An MSNBC Show",
    bad_name: "A Hotel Jacuzzi",
    great_name: "Your Dentist's Hands",
  },
  {
    punchline: "The Desperate Hour",
    good_name: "A Thriller Movie",
    bad_name: "The Bathroom Line at Chipotle",
    great_name: "A Bar at 1:45 A.M.",
  },
  {
    punchline: "Nutty Buddy",
    good_name: "A Peanut Butter Cookie",
    bad_name: "An Allergy Medication",
    great_name: "A Jock Strap",
  },
  {
    punchline: "Warzone",
    good_name: "A Call of Duty Game",
    bad_name: "A Daycare Center",
    great_name: "The Milk Station at Starbucks",
  },
  {
    punchline: "Only Murders in the Building",
    good_name: "A Show on Hulu",
    bad_name: "A Zillow Listing",
    great_name: "Red Lobster",
  },
  {
    punchline: "Paper Source",
    good_name: "A Store That Sells Stationery",
    bad_name: "A Forest",
    great_name: "A CVS Receipt Printer",
  },
  {
    punchline: "Venom: Let There Be Carnage",
    good_name: "A Venom Sequel",
    bad_name: "A Zoo",
    great_name: "Tj Maxx",
  },
  {
    punchline: "Machine Gun Kelly",
    good_name: "A Rapper",
    bad_name: "A New Barbie Doll",
    great_name: "Kelly Clarkson's Call of Duty Screenname",
  },
  {
    punchline: "Shang-Chi and the Legend of the Ten Rings",
    good_name: "A Marvel Movie",
    bad_name: "Your Bathtub",
    great_name: "Tom Brady's Autobiography",
  },
  {
    punchline: "Cry Macho",
    good_name: "A Clint Eastwood Movie",
    bad_name: "A WWE Wrestler",
    great_name: "Ghost Pepper Hot Sauce",
  },
  {
    punchline: "Back Blood",
    good_name: "A Video Game",
    bad_name: "The Red Cross",
    great_name: "A Vampire Boy Band",
  },
  {
    punchline: "Truth Be Told",
    good_name: "An Apple TV+ Show",
    bad_name: "Bathroom Scales",
    great_name: "Tequila",
  },
  {
    punchline: "Bad Trip",
    good_name: "An Eric Andre Movie",
    bad_name: "A Weed Dispensary",
    great_name: "Any Cruise Ship",
  },
  {
    punchline: "Wipeout",
    good_name: "A Reality Competition",
    bad_name: "A Motorcycle Company",
    great_name: "Matt Gaetz's Political Career",
  },
  {
    punchline: "CDC",
    good_name: "The Centers for Disease Control",
    bad_name: "A Washington D.C. Tour Bus",
    great_name: "A Three-Man ACDC Cover Band",
  },
  {
    punchline: "Leave The Door Open",
    good_name: "A Bruno Mars and Anderson .Paak Song",
    bad_name: "A Public Restroom",
    great_name:
      "For What Pete Buttigieg Asks His Mom to do When He Goes To Sleep At Night",
  },
  {
    punchline: "One Too Many",
    good_name: "A Keith Urban and Pink Song",
    bad_name: "A Tattoo Parlor",
    great_name: "The Godfather Trilogy",
  },
  {
    punchline: "God Only Knows",
    good_name: "A Beach Boys Song",
    bad_name: "A Financial Advisor",
    great_name: "Whatever The Most Up-To-Date CDC Guidelines Are",
  },
  {
    punchline: "Tiktok",
    good_name: "A Video App",
    bad_name: "A Retirement Home",
    great_name: "The Cuomo Administration",
  },
  {
    punchline: "Beautiful Mistakes",
    good_name: "A Maroon 5 Song",
    bad_name: "A Delivery Ward",
    great_name: "Finding An Onion Ring In Your Fries",
  },
  {
    punchline: "5 Seconds of Summers",
    good_name: "A Pop Band",
    bad_name: "A Hotel Vacation Package",
    great_name: "August In Alaska",
  },
  {
    punchline: "Bibbidi-Bobbidi-Boo",
    good_name: "A Magic Spell",
    bad_name: "A Scatting Ghost",
    great_name: "Cindirella's Sidepiece",
  },
  {
    punchline: "Handball",
    good_name: "A Sport",
    bad_name: "A Meatball Restaurant",
    great_name: "A Urologist",
  },
  {
    punchline: "Bad Habits",
    good_name: "An Ed Sheeran Song",
    bad_name: "A Cigarette Company",
    great_name: "A Nun Biker Gang",
  },
  {
    punchline: "Permission To Dance",
    good_name: "A BTS Song",
    bad_name: "A James Bond Movie",
    great_name: "Tequila",
  },
  {
    punchline: "Gone In 60 Seconds",
    good_name: "A Nicolas Cage Movie",
    bad_name: "Your New Year's Resolution",
    great_name: "CVS's Supply of At-Home Covid Tests",
  },
  {
    punchline: "Fall Out Boy",
    good_name: "A Pop Punk Band",
    bad_name: "A Baby Bjorn",
    great_name: "A Skydiving School",
  },
  {
    punchline: "Yellowstone",
    good_name: "A TV Western",
    bad_name: "A Jewelry Store",
    great_name: "The Gravel at a Dog Park",
  },
  {
    punchline: "Who Want Smoke??",
    good_name: "A Song by Nardo Wick",
    bad_name: "An Air Filtration System",
    great_name: "A Vape Store Owned by a Caveman",
  },
  {
    punchline: "Nightmare Alley",
    good_name: "A Movie",
    bad_name: "An Airbnb Listing",
    great_name: "A Proctologist",
  },
  {
    punchline: "The Music Man",
    good_name: "A Musical",
    bad_name: "A Mime",
    great_name: "When Your Mom Is Trying To Remember Post Malone's Name",
  },
  {
    punchline: "That's My Jam",
    good_name: "New Show on NBC",
    bad_name: "A Spotify Playlist That's Just Four Hours of 'Whale Sounds'",
    great_name: "A Fistfight at a Farmer's Market",
  },
  {
    punchline: "How I Met Your Father",
    good_name: "A New TV Show",
    bad_name: "A Sperm Bank",
    great_name: "Maury Show",
  },
];
